spring:
  mail:
    password: rijthpdghhmebegi
    host: smtp.qq.com
    username: 568934101@qq.com
    port: 587
    protocol: smtp
    default-encoding: utf-8
    properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true
        mail.smtp.socketFactory.port: 465
        mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
        mail.smtp.socketFactory.fallback: false
        mail.debug: true

  thymeleaf:
    prefix: classpath:/templates/ #prefix 模板文件地址
    check-template-location: true
    cache: false
    suffix:  .html
    #encoding: UTF-8
    #content-type: text/html
    mode: HTML5


  flyway:
    baselineOnMigrate: true
    locations: classpath:/db/migration/ # sql 文件存储地址


  datasource:
      url: jdbc:mysql://localhost:3306/insight?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: 123321
      type: com.alibaba.druid.pool.DruidDataSource
      #项目启动后执行建表语句
      druid:
        filters: stat
        initial-size: 1
        min-idle: 1
        max-active: 20
        #获取连接等待超时时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath:mapper/**/*.xml